### PR TITLE
Updating dependencies and adding github action pipeline

### PR DESCRIPTION
**Pull request by joeyguerra**

### CODE REVIEW

**Review by joh6nn — COMMENTED** [review]
I can't attest that these changes are correct, but they at least look reasonable to me

**Comment by joeyguerra** [comment]
@joh6nn if you do a review and approve it, I can merge it :)

**Comment by joeyguerra** [comment]
Btw, I’m happy to jump on discord to review together.

**Review by joh6nn — APPROVED** [review]
this all looks reasonable enough

**Comment by joeyguerra** [comment]
@technicalpickles @levenleven Can ya'll please help? The checks are not passing and blocking this PR. I think we just need to disable the checks in the repo to allow this to merge.

**Pull request merged**
